### ISSUE TITLE
博主的博客域名过期了？

### ISSUE THREAD

**Issue by EtoDemerzel0427** [AceCoooool/MLF-MLT#1]
之前看到博主的博客，觉得写的很好，对我的学习帮助很大。今天打开发现域名已经过期。不知要如何访问？

**Comment by EtoDemerzel0427** [comment]
刚刚发现博主已经换用github pages + hexo来搭建新博客了，用的主题还和我一样。

**Comment by AceCoooool** [comment]
由于个人穷...就没续费那个域名了。现在暂时用的是github的：https://acecoooool.github.io/ 。
